name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.*
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
          template: classic
          base: activity, repositories
          base_indepth: yes
          config_order: base.activity, base.repositories, isocalendar, languages, wakatime
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0% # Display threshold (percentage)
          
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
