name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.*
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # ... other options
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
